### ISSUE TITLE
Compatibility with RabbitMQ v3.4.4

### ISSUE THREAD

**Issue by XDex** [tonyg/udp-exchange#6]
Hi Tony!
I'm running RabbitMQ v3.4.4. I tried testing both v3.3.0 and v3.5.1 of the plugin, and neither of them seem to work.
I can see the listener is started on the designated port after x-udp exchange creation, however no messages I send are forwarded to bound queues. I've tried binding with \* routing key and with an empty one.
I've tried sending both locally and from a remote host, and the messages are received on the designated network interfaces/ports (checked with tcpdump sniffing)
Unfortunately I can't upgrade RabbitMQ to a newer version due to issues with another plugin, could you please recommend a workaround?
Thanks!

**Comment by tonyg** [comment]
Hi XDex,

It's possible that you will be able to get it working by simply recompiling against RabbitMQ v3.4.4. There were no code changes to the plugin between the 3.3.0 and 3.5.1 releases - only changes in core RabbitMQ server header files. Are you able to give this a try?

Cheers,
  Tony

**Comment by XDex** [comment]
Hi!
Yes, I've compiled a few other plugins before.. Could you post some detailed instructions?
Thanks!

**Comment by tonyg** [comment]
It should be as simple as checking it out into the rabbitmq-public-umbrella and then running `make`. There should be no significant differences from the process for building other plugins.

**Comment by gotthardp** [comment]
It works for me with RabbitMQ 3.5.3. The x-udp exchange behaves like a topic exchange and the routing key is composed from several values. Please try binding using **#**.
